### ISSUE TITLE
Key explanation

### ISSUE THREAD

**Issue by hellopanictech** [gszathmari/homelab-on-oracle-cloud#1]
If you mess up a variable in your build, its quite a pain to tear down your infrastructure in OCI. One thing I messed up, didn't realize the private key path was for the API key and the ssh public key was not the same as the api public key. They need to be the corrected formats. Its outlined in the OCI docs, but it might be cool to add a blip in your readme to save some hassle.

**Comment by gszathmari** [comment]
No worries, I am happy to expand the readme. Do you refer to this, @hellopanictech ? https://github.com/gszathmari/homelab-on-oracle-cloud/blob/main/terraform/terraform.tfvars#L4=

**Comment by hellopanictech** [comment]
Yes, thats the spot. Maybe just a comment that its the API private key, and then below, it requires the SSH public key for future logins.

Also, I'm having another issue with my region ASHBURN because it has 3 availability domains. It looks like Error Message: shape VM.Standard.E2.1.Micro not found because the build-out defaults to use ADmD:US-ASHBURN-AD-1 where Micro VMs are not available. They are available in ADmD:US-ASHBURN-AD-2, is there a way I can force the code to use that second AD instead of using the 1st one automatically? I was hoping to use that region since its closest to home. Thanks!

**Comment by gszathmari** [comment]
Thank you for the bug report, @hellopanictech, hopefully #2 clarifies things up.
